all:
	g++ -o test test_read.cpp -I/home/liuli/2018trc/autopilot-thirdparty/thirdparty/caffe/install/include   -L/usr/local/cuda-7.5/targets/x86_64-linux/lib/ -lcaffe -I/usr/local/cuda/targets/x86_64-linux/include/ -lboost_system
